name: PR Checks
on:
  push:
  
    branches: [ main, release/* ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Secret Scan
        uses: trufflesecurity/trufflehog@v3
        with: { path: ., fail: true }
      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3
        with: { file_or_dir: k8s/ }
      - name: Dockerfile Lint
        uses: hadolint/hadolint-action@v3
        with: { dockerfile: docker/ }
